### ISSUE TITLE
Local Storage security error

### ISSUE THREAD

**Issue by dmvaldman** [tangrams/tangram-tutorial#1]
Got this error when loading https://tangrams.github.io/tangram-tutorial/tangram-tutorial/build/

None of the CodeMirror text fields populated

```
tangram-play.js:25 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

<img width="580" alt="screen shot 2016-07-11 at 3 38 04 pm" src="https://cloud.githubusercontent.com/assets/796394/16744119/8d5879c6-477d-11e6-8381-f40629b135e8.png">

**Comment by irealva** [comment]
I'm temporarily removing local storage from this branch of embedded play. We'll figure out what makes sense in terms of widget and localstorage once we decide how and where the tutorial will exist. 

Thanks @louh and @dmvaldman.
